INSERT INTO customers (Name, Email, City, Country, CustomerSegment) VALUES
('Samantha Morton', 'samantha.morton@example.com', 'Vienna', 'Austria', 'Standard'),
('David Wood', 'david.wood@example.com', 'Dublin', 'Ireland', 'Premium'),
('Sara Hensley', 'sara.hensley@example.com', 'Helsinki', 'Finland', 'Standard'),
('Kimberly Weaver', 'kimberly.weaver@example.com', 'Warsaw', 'Poland', 'Premium'),
('Devin Hooper', 'devin.hooper@example.com', 'Dublin', 'Ireland', 'Premium'),
('Christian Lawson', 'christian.lawson@example.com', 'Vienna', 'Austria', 'Standard'),
('Allison Horn', 'allison.horn@example.com', 'Lisbon', 'Portugal', 'Premium'),
('Robert Carter', 'robert.carter@example.com', 'Stockholm', 'Sweden', 'Standard'),
('Stephen Scott', 'stephen.scott@example.com', 'Berlin', 'Germany', 'Standard'),
('Jacqueline Barrett', 'jacqueline.barrett@example.com', 'Berlin', 'Germany', 'Standard'),
('Laura Craig', 'laura.craig@example.com', 'Prague', 'Czech Republic', 'Premium'),
('Willie Hampton', 'willie.hampton@example.com', 'Copenhagen', 'Denmark', 'Premium'),
('Rhonda Cooper', 'rhonda.cooper@example.com', 'Prague', 'Czech Republic', 'Standard'),
('Joe Martin', 'joe.martin@example.com', 'Oslo', 'Norway', 'Standard'),
('David Holmes', 'david.holmes@example.com', 'Helsinki', 'Finland', 'Standard'),
('Alejandro Owen', 'alejandro.owen@example.com', 'Madrid', 'Spain', 'Premium'),
('Sarah Anthony', 'sarah.anthony@example.com', 'Dublin', 'Ireland', 'Premium'),
('Maria Newman', 'maria.newman@example.com', 'Copenhagen', 'Denmark', 'Standard'),
('Kimberly Levine', 'kimberly.levine@example.com', 'Lisbon', 'Portugal', 'Standard'),
('Barbara Diaz', 'barbara.diaz@example.com', 'Lisbon', 'Portugal', 'Standard'),
('Teresa Dunn', 'teresa.dunn@example.com', 'Berlin', 'Germany', 'Premium'),
('Carol Green', 'carol.green@example.com', 'Stockholm', 'Sweden', 'Premium'),
('Christopher Morgan', 'christopher.morgan@example.com', 'Stockholm', 'Sweden', 'Premium'),
('Mary Cooley', 'mary.cooley@example.com', 'Zurich', 'Switzerland', 'Standard'),
('Cindy Russell', 'cindy.russell@example.com', 'Warsaw', 'Poland', 'Premium'),
('Raymond Garcia', 'raymond.garcia@example.com', 'Budapest', 'Hungary', 'Premium'),
('Jeremy Nichols', 'jeremy.nichols@example.com', 'Zurich', 'Switzerland', 'Premium'),
('Jeff Herrera', 'jeff.herrera@example.com', 'Copenhagen', 'Denmark', 'Premium'),
('Mark Love', 'mark.love@example.com', 'Prague', 'Czech Republic', 'Premium'),
('Karen Powell', 'karen.powell@example.com', 'Oslo', 'Norway', 'Standard'),
('Stephen Saunders', 'stephen.saunders@example.com', 'Stockholm', 'Sweden', 'Standard'),
('Rebecca Griffin', 'rebecca.griffin@example.com', 'Vienna', 'Austria', 'Standard'),
('Lee Adams', 'lee.adams@example.com', 'Amsterdam', 'Netherlands', 'Standard'),
('Lori Ballard', 'lori.ballard@example.com', 'Stockholm', 'Sweden', 'Standard'),
('Beth Osborne', 'beth.osborne@example.com', 'Brussels', 'Belgium', 'Standard'),
('Sarah Carter', 'sarah.carter@example.com', 'Lisbon', 'Portugal', 'Standard'),
('Brandon Wade', 'brandon.wade@example.com', 'Warsaw', 'Poland', 'Premium'),
('Lisa Williams', 'lisa.williams@example.com', 'Rome', 'Italy', 'Standard'),
('Rebecca Young', 'rebecca.young@example.com', 'Stockholm', 'Sweden', 'Standard'),
('Joshua Cole', 'joshua.cole@example.com', 'Prague', 'Czech Republic', 'Premium'),
('Gary Cameron', 'gary.cameron@example.com', 'Vienna', 'Austria', 'Standard'),
('Nancy Kramer', 'nancy.kramer@example.com', 'Athens', 'Greece', 'Premium'),
('Christina Cole', 'christina.cole@example.com', 'Amsterdam', 'Netherlands', 'Standard'),
('Darlene Ramsey', 'darlene.ramsey@example.com', 'Vienna', 'Austria', 'Standard'),
('Rebecca Collins', 'rebecca.collins@example.com', 'Lisbon', 'Portugal', 'Standard'),
('Kevin Parker', 'kevin.parker@example.com', 'Prague', 'Czech Republic', 'Standard'),
('Caitlin Fitzgerald', 'caitlin.fitzgerald@example.com', 'Copenhagen', 'Denmark', 'Premium'),
('Kevin Lawrence', 'kevin.lawrence@example.com', 'Copenhagen', 'Denmark', 'Standard'),
('Adam Perez', 'adam.perez@example.com', 'Helsinki', 'Finland', 'Standard'),
('Andrew Lynn', 'andrew.lynn@example.com', 'Lisbon', 'Portugal', 'Standard'),
('Matthew Torres', 'matthew.torres@example.com', 'Zurich', 'Switzerland', 'Standard'),
('Calvin Welch', 'calvin.welch@example.com', 'Oslo', 'Norway', 'Premium'),
('Daniel White', 'daniel.white@example.com', 'Berlin', 'Germany', 'Premium'),
('Susan Hayes', 'susan.hayes@example.com', 'Copenhagen', 'Denmark', 'Standard'),
('Mrs. Anne Atkins', 'mrs..anne atkins@example.com', 'Lisbon', 'Portugal', 'Standard'),
('Stacey Kim', 'stacey.kim@example.com', 'Dublin', 'Ireland', 'Standard'),
('Logan Sanchez', 'logan.sanchez@example.com', 'Paris', 'France', 'Premium'),
('Victor Lopez', 'victor.lopez@example.com', 'Paris', 'France', 'Standard'),
('Kyle Ferguson', 'kyle.ferguson@example.com', 'Stockholm', 'Sweden', 'Standard'),
('Brian Bowen', 'brian.bowen@example.com', 'Brussels', 'Belgium', 'Premium'),
('Rachel Roberts', 'rachel.roberts@example.com', 'Vienna', 'Austria', 'Premium'),
('Natasha Snyder', 'natasha.snyder@example.com', 'Rome', 'Italy', 'Premium'),
('Shane Montoya', 'shane.montoya@example.com', 'Brussels', 'Belgium', 'Premium'),
('Andrea Andrews', 'andrea.andrews@example.com', 'Helsinki', 'Finland', 'Standard'),
('Samantha Sims', 'samantha.sims@example.com', 'Amsterdam', 'Netherlands', 'Standard'),
('Adam Hale', 'adam.hale@example.com', 'Rome', 'Italy', 'Standard'),
('Rebecca Ward', 'rebecca.ward@example.com', 'Dublin', 'Ireland', 'Premium'),
('Calvin Butler', 'calvin.butler@example.com', 'Dublin', 'Ireland', 'Premium'),
('Angela Bailey', 'angela.bailey@example.com', 'Brussels', 'Belgium', 'Premium'),
('Scott Thomas', 'scott.thomas@example.com', 'Paris', 'France', 'Standard'),
('Jasmine Huynh', 'jasmine.huynh@example.com', 'Madrid', 'Spain', 'Standard'),
('Brandi Hebert', 'brandi.hebert@example.com', 'Brussels', 'Belgium', 'Premium'),
('Dana Kelly', 'dana.kelly@example.com', 'Zurich', 'Switzerland', 'Standard'),
('Willie Roberson', 'willie.roberson@example.com', 'Berlin', 'Germany', 'Premium'),
('Laura Blanchard', 'laura.blanchard@example.com', 'Zurich', 'Switzerland', 'Standard'),
('Raymond Kirk', 'raymond.kirk@example.com', 'Paris', 'France', 'Premium'),
('Lisa Bryan', 'lisa.bryan@example.com', 'Brussels', 'Belgium', 'Standard'),
('Anna Young', 'anna.young@example.com', 'Warsaw', 'Poland', 'Premium'),
('Dominique Young', 'dominique.young@example.com', 'Stockholm', 'Sweden', 'Premium'),
('Tammy Kirk', 'tammy.kirk@example.com', 'Brussels', 'Belgium', 'Standard'),
('Steven Hall', 'steven.hall@example.com', 'Budapest', 'Hungary', 'Premium'),
('William Willis', 'william.willis@example.com', 'Madrid', 'Spain', 'Premium'),
('Stephanie Adams', 'stephanie.adams@example.com', 'Berlin', 'Germany', 'Standard'),
('Michelle Banks', 'michelle.banks@example.com', 'Stockholm', 'Sweden', 'Premium'),
('Kyle Griffin', 'kyle.griffin@example.com', 'Prague', 'Czech Republic', 'Premium'),
('Thomas Walsh', 'thomas.walsh@example.com', 'Stockholm', 'Sweden', 'Premium'),
('Yvonne Pugh', 'yvonne.pugh@example.com', 'Rome', 'Italy', 'Standard'),
('Amber Cook', 'amber.cook@example.com', 'Berlin', 'Germany', 'Premium'),
('Dr. Brianna Griffin', 'dr..brianna griffin@example.com', 'Oslo', 'Norway', 'Premium'),
('Thomas Melton', 'thomas.melton@example.com', 'Athens', 'Greece', 'Premium'),
('Juan Floyd', 'juan.floyd@example.com', 'Rome', 'Italy', 'Premium'),
('Anna Tate', 'anna.tate@example.com', 'Vienna', 'Austria', 'Premium'),
('Charles Woodard', 'charles.woodard@example.com', 'Helsinki', 'Finland', 'Standard'),
('James Rodriguez', 'james.rodriguez@example.com', 'Dublin', 'Ireland', 'Standard'),
('Jeffrey Rivas', 'jeffrey.rivas@example.com', 'Stockholm', 'Sweden', 'Premium'),
('Kari Sanchez', 'kari.sanchez@example.com', 'Prague', 'Czech Republic', 'Premium'),
('Brandon Jordan', 'brandon.jordan@example.com', 'Helsinki', 'Finland', 'Premium'),
('Samuel Thomas', 'samuel.thomas@example.com', 'Stockholm', 'Sweden', 'Standard'),
('Jennifer Watson', 'jennifer.watson@example.com', 'Copenhagen', 'Denmark', 'Standard'),
('Alexa Mccall', 'alexa.mccall@example.com', 'Rome', 'Italy', 'Premium');